[package]
name = "echo-server"
version = "0.1.0"
authors = ["David Li <davidli2010@foxmail.com>"]

[dependencies]
mio = "0.6"
byteorder = "^1.2"
bytes = "0.4"
log = "0.4"
env_logger = "0.5"

[[bin]]
name = "echo-server"
path = "src/main.rs"

[[bin]]
name = "echo-client"
path = "src/client.rs"